#version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "python app.py"

  question_generator:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    command: python question_generator.py

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=trivia_db
      - POSTGRES_USER=trivia_user
      - POSTGRES_PASSWORD=trivia_password

volumes:
  postgres_data:
